language: node_js
node_js:
  - v9.4.0
cache:
  directories:
    - node_modules
  yarn: true
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
install: yarn install --pure-lockfile
script:
  - yarn run lint
  - nohup yarn run ganache &
  - yarn test
  - if [ -n "$COVERALLS_REPO_TOKEN" ]; then yarn run test:coveralls; fi
  - yarn run build
notifications:
  slack: kleros:Ub8n81EgKJ3iRrMDyWyQIVJp
